import type { NewDecision, NewHypothesis } from '@pca/shared';

/**
 * Deterministic demo hypotheses + decisions in full structured format, so `./run.sh` shows a
 * genuinely detailed multi-page report without an OAuth token or manual data entry. Each passes
 * validateHypothesis (≥3 assumptions across behavior/market/tech, ≥2 distinct method types,
 * rationales, traffic-light, deadline). Decisions reference hypotheses by 1-based index into the
 * array returned by {@link buildSeedHypotheses} — the seeder remaps these to real DB ids.
 */
export function buildSeedHypotheses(): NewHypothesis[] {
  return [
    {
      diamondPhase: 'define',
      kind: 'problem',
      subject: 'Слушатели подкаста',
      action: 'оставляют заявку, но не оплачивают',
      solution: 'покупку билета',
      condition: 'оплата требует ручного выставления счёта',
      title: 'Подкаст-трафик даёт заявки без оплат',
      description:
        'Канал podcast приносит больше всего визитов, но конверсия в оплату ниже среднего — заявки «остывают» на ручном счёте.',
      hiddenAssumptions: [
        {
          category: 'behavior',
          text: 'Слушатель готов платить сразу, если оплата онлайн в 1 клик.',
        },
        {
          category: 'market',
          text: 'Аудитория подкаста платёжеспособна и принимает решение быстро.',
        },
        { category: 'tech', text: 'Текущий путь оплаты ломается на этапе ручного счёта.' },
      ],
      validationMethods: [
        {
          type: 'quantitative',
          plan: 'Сегментировать воронку podcast → заявка → оплата по дням.',
          cost: 'низкая',
        },
        {
          type: 'live',
          plan: 'Включить онлайн-оплату для 50% podcast-трафика (A/B).',
          cost: 'средняя',
        },
      ],
      impact: 9,
      confidence: 7,
      ease: 6,
      impactRationale:
        'Podcast — крупнейший канал по визитам, рост его конверсии двигает общий KPI.',
      confidenceRationale: 'Разрыв заявка→оплата виден в данных, но причинность ещё не доказана.',
      easeRationale: 'Онлайн-оплата требует интеграции эквайринга — несколько дней работы.',
      greenCriteria: 'Конверсия podcast в оплату выросла на ≥30% за 2 недели A/B.',
      yellowCriteria: 'Рост 10–30% — продолжаем, но ищем дополнительные причины отвала.',
      redCriteria: 'Рост <10% или нет значимой разницы — причина не в способе оплаты.',
      deadlineDays: 14,
      evidence: [
        {
          type: 'channel_stats',
          slice: 'channel=podcast',
          note: 'CR в оплату ниже direct при большем трафике.',
        },
      ],
    },
    {
      diamondPhase: 'define',
      kind: 'problem',
      subject: 'Посетители страницы /checkout',
      action: 'уходят',
      solution: 'оформление оплаты',
      condition: 'на чек-ауте нет понятных способов оплаты',
      title: 'Высокий отказ на /checkout',
      description:
        'Страница выхода /checkout имеет высокий bounce — теряем уже «горячих» пользователей.',
      hiddenAssumptions: [
        { category: 'behavior', text: 'Пользователь доходит до checkout с намерением купить.' },
        { category: 'tech', text: 'Форма оплаты тормозит или содержит ошибки на мобильных.' },
        { category: 'market', text: 'Цена на этом этапе не является блокером.' },
      ],
      validationMethods: [
        {
          type: 'quantitative',
          plan: 'Проанализировать bounce и время на /checkout по устройствам.',
        },
        {
          type: 'synthetic',
          plan: 'Синтетический CustDev: проиграть путь оплаты глазами 3 персон.',
        },
      ],
      impact: 8,
      confidence: 6,
      ease: 7,
      impactRationale: 'Отвал на checkout — это потеря самых конверсионных пользователей.',
      confidenceRationale: 'Высокий bounce подтверждён, но причина (UX/цена/тех) не выделена.',
      easeRationale: 'Диагностика дешёвая; правки формы — средняя сложность.',
      greenCriteria: 'Bounce /checkout снижен на ≥20% после правок формы.',
      yellowCriteria: 'Снижение 5–20% — частичный эффект, нужны итерации.',
      redCriteria: 'Без изменений — причина не в самой форме.',
      deadlineDays: 10,
    },
    {
      diamondPhase: 'define',
      kind: 'problem',
      subject: 'Мобильные пользователи из России',
      action: 'конвертируются хуже',
      solution: 'десктопной аудитории',
      condition: 'мобильная вёрстка лендинга неудобна',
      title: 'Мобильная конверсия ниже десктопной',
      description:
        'Гео+устройство показывают, что mobile даёт больше визитов, но меньше заявок на визит.',
      hiddenAssumptions: [
        {
          category: 'behavior',
          text: 'Мобильные пользователи готовы покупать, но спотыкаются о UX.',
        },
        { category: 'tech', text: 'Лендинг не оптимизирован под мобильные экраны.' },
        { category: 'market', text: 'Доля мобильного трафика продолжит расти.' },
      ],
      validationMethods: [
        { type: 'quantitative', plan: 'Сравнить CR mobile vs desktop по гео-срезам.' },
        { type: 'live', plan: 'Выкатить мобильную оптимизацию ключевых экранов и замерить.' },
      ],
      impact: 7,
      confidence: 6,
      ease: 5,
      impactRationale: 'Mobile — растущая доля трафика, разрыв конверсии масштабируется.',
      confidenceRationale: 'Разрыв виден, но смешан с источником трафика.',
      easeRationale: 'Мобильная переверстка — несколько дней дизайна и фронта.',
      greenCriteria: 'CR mobile приблизился к desktop в пределах 15%.',
      yellowCriteria: 'Сокращение разрыва, но >15% — продолжаем.',
      redCriteria: 'Разрыв не сократился — причина не в вёрстке.',
      deadlineDays: 21,
    },
    {
      diamondPhase: 'define',
      kind: 'problem',
      subject: 'Команда трека',
      action: 'не приоритизирует гипотезы',
      solution: 'единый дашборд',
      condition: 'данные размазаны по Excel-выгрузкам',
      title: 'Нет единой приоритизации гипотез',
      description:
        'Гипотезы живут в чатах без ICE и привязки к данным — решения принимаются на ощущениях.',
      hiddenAssumptions: [
        {
          category: 'behavior',
          text: 'Команда будет вести гипотезы в инструменте, если это быстро.',
        },
        { category: 'market', text: 'Методология Воронковой подходит для этой задачи.' },
        { category: 'tech', text: 'Дашборд способен связать гипотезу с raw_responses.' },
      ],
      validationMethods: [
        { type: 'synthetic', plan: 'Прогнать 3 текущие идеи через ICE и сравнить с интуицией.' },
        { type: 'live', plan: 'Дать команде завести ≥5 гипотез за неделю.' },
      ],
      impact: 6,
      confidence: 8,
      ease: 7,
      impactRationale: 'Приоритизация экономит недели работы на неважных задачах.',
      confidenceRationale: 'Подход проверен в методологии Воронковой.',
      easeRationale: 'Функционал уже есть в дашборде.',
      greenCriteria: '≥5 гипотез заведено и приоритизировано за неделю.',
      yellowCriteria: '2–4 гипотезы — частичное принятие.',
      redCriteria: 'Команда продолжает работать в Excel.',
      deadlineDays: 7,
    },
    {
      diamondPhase: 'develop',
      kind: 'solution',
      subject: 'Команда трека',
      action: 'внедрит онлайн-оплату',
      solution: 'эквайринг с оплатой в 1 клик',
      condition: 'это поднимет конверсию podcast-трафика в оплату',
      title: 'Онлайн-оплата в 1 клик',
      description:
        'Решение для гипотезы №1: убрать ручной счёт, дать мгновенную оплату картой/СБП.',
      parentId: 1,
      hiddenAssumptions: [
        { category: 'behavior', text: 'Пользователи доверяют онлайн-оплате на лендинге.' },
        { category: 'tech', text: 'Эквайринг интегрируется без долгой модерации.' },
        { category: 'market', text: 'Комиссия эквайринга приемлема для юнит-экономики.' },
      ],
      validationMethods: [
        { type: 'live', plan: 'A/B: онлайн-оплата vs ручной счёт на podcast-трафике.' },
        { type: 'quantitative', plan: 'Сравнить конверсию в оплату до/после по когортам.' },
      ],
      impact: 9,
      confidence: 7,
      ease: 6,
      impactRationale: 'Прямо бьёт по крупнейшему каналу и его слабому месту.',
      confidenceRationale: 'A/B даст чистый сигнал по причинности.',
      easeRationale: 'Интеграция эквайринга — основной объём работы.',
      greenCriteria: 'Конверсия в оплату +30% на тестовой группе.',
      yellowCriteria: '+10–30% — масштабируем осторожно.',
      redCriteria: '<10% — способ оплаты не главная причина.',
      deadlineDays: 14,
    },
    {
      diamondPhase: 'develop',
      kind: 'solution',
      subject: 'Команда трека',
      action: 'упростит форму оплаты',
      solution: 'мобильный чек-аут в один экран',
      condition: 'это снизит отказ на /checkout',
      title: 'Одноэкранный мобильный чек-аут',
      description: 'Решение для гипотез №2 и №3: собрать оплату в один короткий мобильный экран.',
      parentId: 2,
      hiddenAssumptions: [
        { category: 'behavior', text: 'Меньше полей → выше доходимость до оплаты.' },
        { category: 'tech', text: 'Короткую форму можно собрать на текущем стеке.' },
        { category: 'market', text: 'Конкуренты уже дают быстрый мобильный чек-аут.' },
      ],
      validationMethods: [
        { type: 'live', plan: 'Выкатить новый чек-аут на 50% мобильного трафика.' },
        { type: 'synthetic', plan: 'Проиграть новый путь глазами 3 мобильных персон.' },
      ],
      impact: 8,
      confidence: 6,
      ease: 6,
      impactRationale: 'Снижает отвал на самом конверсионном этапе для растущей mobile-доли.',
      confidenceRationale: 'Гипотеза опирается на bounce-данные, но нужен живой тест.',
      easeRationale: 'Переработка формы — средний объём фронт-работы.',
      greenCriteria: 'Bounce /checkout на mobile −20%.',
      yellowCriteria: '−5…−20% — итерируем.',
      redCriteria: 'Без изменений — причина не в форме.',
      deadlineDays: 12,
    },
    {
      diamondPhase: 'develop',
      kind: 'solution',
      subject: 'Маркетинг трека',
      action: 'перераспределит бюджет',
      solution: 'усиление каналов с высокой оплатой',
      condition: 'это повысит число оплат при том же бюджете',
      title: 'Сдвиг бюджета в платящие каналы',
      description:
        'Решение: вкладывать в каналы с высокой конверсией в оплату (direct/referral), а не только в объём.',
      hiddenAssumptions: [
        {
          category: 'market',
          text: 'Каналы с высокой оплатой масштабируются без падения качества.',
        },
        { category: 'behavior', text: 'Качество трафика по каналам стабильно во времени.' },
        { category: 'tech', text: 'Атрибуция по каналам в Метрике достаточно точна.' },
      ],
      validationMethods: [
        { type: 'quantitative', plan: 'Сравнить CPL/CPS по каналам и пересчитать аллокацию.' },
        { type: 'market', plan: 'Оценить ёмкость каналов с лучшей оплатой.' },
      ],
      impact: 7,
      confidence: 5,
      ease: 8,
      impactRationale: 'Перекладка бюджета даёт больше оплат без роста затрат.',
      confidenceRationale: 'Ёмкость лучших каналов под вопросом.',
      easeRationale: 'Перераспределение бюджета — операционно простое действие.',
      greenCriteria: 'Число оплат +15% при том же бюджете за 3 недели.',
      yellowCriteria: '+5–15% — продолжаем оптимизацию.',
      redCriteria: 'Без роста — каналы не масштабируются.',
      deadlineDays: 21,
    },
    {
      diamondPhase: 'develop',
      kind: 'solution',
      subject: 'Команда трека',
      action: 'будет вести гипотезы',
      solution: 'дашборд с ICE и Decision Log',
      condition: 'это ускорит принятие решений на данных',
      title: 'Дисциплина гипотез в дашборде',
      description:
        'Решение для гипотезы №4: единый инструмент с форматом Воронковой, ICE и Decision Log.',
      parentId: 4,
      hiddenAssumptions: [
        { category: 'behavior', text: 'Команда предпочтёт инструмент Excel, если он быстрее.' },
        { category: 'tech', text: 'Каждая цифра прослеживается до raw_responses.' },
        { category: 'market', text: 'Формат Воронковой принят командой как стандарт.' },
      ],
      validationMethods: [
        { type: 'live', plan: 'Неделя работы команды только в дашборде.' },
        { type: 'synthetic', plan: 'Прогнать решённые задачи через Decision Log ретроспективно.' },
      ],
      impact: 6,
      confidence: 8,
      ease: 7,
      impactRationale: 'Дисциплина гипотез повышает качество всех остальных решений.',
      confidenceRationale: 'Методология и инструмент уже готовы.',
      easeRationale: 'Функционал реализован, нужно лишь принятие.',
      greenCriteria: '≥3 человека ведут гипотезы самостоятельно неделю.',
      yellowCriteria: '1–2 человека — частичное принятие.',
      redCriteria: 'Команда вернулась в Excel.',
      deadlineDays: 7,
    },
    {
      diamondPhase: 'define',
      kind: 'problem',
      subject: 'Оставившие заявку',
      action: 'не возвращаются к оплате',
      solution: 'повторное касание',
      condition: 'после заявки нет догрева',
      title: 'Заявки не догреваются до оплаты',
      description:
        'Между заявкой и оплатой нет коммуникации — часть тёплых лидов теряется без напоминания.',
      hiddenAssumptions: [
        { category: 'behavior', text: 'Лиду нужен повод и напоминание, чтобы вернуться к оплате.' },
        { category: 'market', text: 'Email/мессенджеры — приемлемый канал догрева для аудитории.' },
        { category: 'tech', text: 'Контакт лида сохраняется и доступен для рассылки.' },
      ],
      validationMethods: [
        { type: 'quantitative', plan: 'Измерить долю заявок без оплаты и срок «остывания».' },
        { type: 'live', plan: 'Запустить серию писем-догрева на сегмент заявок без оплаты.' },
      ],
      impact: 7,
      confidence: 6,
      ease: 7,
      impactRationale: 'Догрев возвращает уже заинтересованных лидов — дешёвый источник оплат.',
      confidenceRationale: 'Разрыв заявка→оплата виден, эффект догрева ещё не замерен.',
      easeRationale: 'Рассылку можно собрать на текущих контактах за день-два.',
      greenCriteria: 'Догрев вернул к оплате ≥15% заявок без оплаты за 2 недели.',
      yellowCriteria: 'Возврат 5–15% — продолжаем и тюним письма.',
      redCriteria: 'Возврат <5% — догрев не работает для этой аудитории.',
      deadlineDays: 14,
    },
    {
      diamondPhase: 'develop',
      kind: 'solution',
      subject: 'Маркетинг трека',
      action: 'настроит серию догрева',
      solution: 'автоматические письма после заявки',
      condition: 'это вернёт часть заявок к оплате',
      title: 'Email-догрев заявок до оплаты',
      description: 'Решение для гипотезы «Заявки не догреваются»: 3 письма с пользой и оффером.',
      parentId: 9,
      hiddenAssumptions: [
        { category: 'behavior', text: 'Письма открывают и по ним возвращаются к оплате.' },
        { category: 'tech', text: 'Триггерную рассылку можно завести на текущем стеке.' },
        { category: 'market', text: 'Частота 3 письма не вызывает отписок выше нормы.' },
      ],
      validationMethods: [
        { type: 'live', plan: 'A/B: сегмент с догревом против контрольного без писем.' },
        { type: 'quantitative', plan: 'Сравнить долю оплат в когортах с догревом и без.' },
      ],
      impact: 7,
      confidence: 6,
      ease: 7,
      impactRationale: 'Возврат тёплых лидов — прямой прирост оплат при низкой цене.',
      confidenceRationale: 'Нужен живой A/B, чтобы отделить эффект писем от фона.',
      easeRationale: 'Триггерная цепочка из 3 писем — небольшой объём настройки.',
      greenCriteria: 'Когорта с догревом даёт +15% оплат против контроля.',
      yellowCriteria: '+5–15% — масштабируем с доработкой писем.',
      redCriteria: '<5% — письма не влияют на оплату.',
      deadlineDays: 14,
    },
  ];
}

/** Demo Decision Log entries. hypothesisId is a 1-based index into buildSeedHypotheses(). */
export function buildSeedDecisions(): NewDecision[] {
  return [
    {
      hypothesisId: 1,
      date: '2025-01-05',
      method: 'mixed',
      scope: 'A/B онлайн-оплаты на podcast-трафике, 2 недели',
      periodDays: 14,
      findings: [
        { text: 'Онлайн-оплата подняла конверсию podcast в оплату на 24%.', confidence: 'high' },
        { text: 'Часть пользователей всё ещё уходит на этапе ввода карты.', confidence: 'medium' },
      ],
      evidence: [
        {
          quote: 'Платёж прошёл за 10 секунд, наконец-то без счёта.',
          source: 'CustDev, респондент 2',
        },
      ],
      outcome: 'yellow',
      outcomeRationale:
        'Рост попал в жёлтую зону (10–30%) — масштабируем, но дорабатываем ввод карты.',
      nextStep: 'Упростить шаг ввода карты и повторить замер.',
      responsible: 'Сергей',
      decidedBy: 'Команда трека',
      participants: 'Лиза, Сергей',
    },
    {
      hypothesisId: 4,
      date: '2025-01-05',
      method: 'live',
      scope: 'Неделя ведения гипотез в дашборде',
      periodDays: 7,
      findings: [
        { text: 'Команда завела 6 гипотез с полным форматом Воронковой.', confidence: 'high' },
        { text: 'ICE-приоритизация поменяла порядок задач против интуиции.', confidence: 'high' },
      ],
      evidence: [{ quote: 'Сразу видно, что бить первым.', source: 'Ретро команды трека' }],
      outcome: 'green',
      outcomeRationale:
        'Превышен порог в 5 гипотез, команда работает в инструменте самостоятельно.',
      nextStep: 'Зафиксировать дашборд как основной инструмент трека.',
      decidedBy: 'Команда трека',
    },
  ];
}
